var TREEVIEW_ACTION_TYPES = {
  EDIT_HYPER_LINK: 'EDIT_HYPER_LINK',
  EDIT_FOLDER: 'EDIT_FOLDER',
  ADD_SUB_FOLDER: 'ADD_SUB_FOLDER',
  ADD_HYPER_LINK: 'ADD_HYPER_LINK',
  SHARE_ITEM: 'SHARE_ITEM'
}

var NODE_TYPES = {
  FOLDER: 'folder',
  HYPER_LINK: 'hyperLink',
}
